server:
  port: 8080

toiletto:
  app:
    jwtSecret: apwoefij823rf89ps3p2fipaw98w39j83329823f982jf0239f8j230f982j3f09283fj02398fj2039f8j2309f8j2039f8j20398fj203f982j30f9283jf02938fj
    jwtExpirationMs: 86400000

spring:
  # Database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/toiletfinder
    username: postgres
    password: jw603492
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
      # Avoid issue with JPA case insensitive
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # This should no longer be needed with Hibernate 6
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: true
    database: postgresql
    # PotGIS configuration
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.type.descriptor.sql: trace